spring.application.name=backend

openweather.base-url=https://api.openweathermap.org
ignav.base-url=https://ignav.com/api
googleplaces.base-url=https://places.googleapis.com/v1

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=5

server.servlet.context-path=/api
travelplanner.jwt.secret=${TRAVEL_PLANNER_JWT_SECRET}
travelplanner.jwt.expiration-ms=${TRAVEL_PLANNER_JWT_EXPIRATION_MS}
